### PR TITLE
Add LogisticRegression with sigmoid outputs

### PR DESCRIPTION
**Pull request by corneliusboehm**
Add support for sigmoid outputs in the `LogisticRegression` class (not used anywhere yet)

### CODE REVIEW

**Comment by sunny-panchal** [comment]
Is it intended as an activation function before the softmax or would you use either one exclusively?

**Comment by corneliusboehm** [comment]
> Is it intended as an activation function before the softmax or would you use either one exclusively?

Theoretically, I've left it open, but in practice I have only used them exclusively. Do you think we should make sure to only use either or?

**Comment by sunny-panchal** [comment]
> > Is it intended as an activation function before the softmax or would you use either one exclusively?
> 
> Theoretically, I've left it open, but in practice I have only used them exclusively. Do you think we should make sure to only use either or?

Not sure... I don't believe sigmoid would be a good activation before a softmax in general in case of saturation so there may never be a reason to use them together. I was also wondering if it would make sense instead to have a separate sub-class of the logistic regression with the sigmoid output layer instead.

**Comment by corneliusboehm** [comment]
Made it its own subclass now, which also makes sure to disable softmax

**Comment by corneliusboehm** [comment]
Rebased this branch on `master` now so we can already merge it

**Review by sunny-panchal — APPROVED** [review]
lgtm :+1:

**Pull request merged**
