### PR TITLE
[Gesture Recognition] Confusion between left and right labels

### PR DESCRIPTION
**Pull request by manikd31**
This PR swaps the left and right labels for `Pointing` and `Swiping` actions on the gesture_recognition demo.

### CODE REVIEW

**Review by nahuakang — APPROVED** [review]
Let's merge this into my branch :muscle:

**Comment by corneliusboehm** [comment]
@manikd31 Did you find out if this has something to do with flipping the video in the wrong place?

**Comment by manikd31** [comment]
> @manikd31 Did you find out if this has something to do with flipping the video in the wrong place? This is probably also relevant for the fitness tracker example where some moves are side-specific.

@corneliusboehm I tried the `gesture-recognition` script using live video (web-cam) as well as recorded videos, and it seemed to work fine with the swap of labels. For clarity, I will go through the other demo scripts as well.

**Comment by manikd31** [comment]
This change might not be necessary, found the issue elsewhere. Check #107.

**Pull request closed without merging**
